before_install:
- gem install bundler
language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: pRQWOtnmLApFsdgeb6sQyLC2C8hWQ4rpHUOrHHhxPHKDtcM0kfoFqwo4GvqaJSHpXS4ah7AM3VakoUKuxYObHYIJGOLt+w3ktgPUmWoceYdvGMmBfehe3h+nZ953ftNB8ggtdicxDbe7dYaRZqhgBcL8JKK4dHJipjKUfpYpIMh/SdCmFx+gLWsjg3/jy7qjI6h7IRutc6oRoGC2r7oz2CZtA6hPC3jBMvwPl5ZVak1PoNNV8xyPnEBoAQElXy0pCsGcyihePeMaANYPEyfRmOiwbW4Mw4EYp3323zSVFsWpIrnSWxurF0+teypGslA+JGgKhUWk+lxp3iP5Oi0l7xTJFeHuWdIoKuB1D3RHnNhK2XYs1r6S6JqdfJFo/JAnU0IPvQxJ3ijFPW6hTpXVDXcZ3w3Hh8GUAzhVdE1eXPFyTCdpeUetYD1ZWbA0z1ZsOuX8CorEeDcluKfTRqCZh65+SFrSmVuLdi1CkYnNa48bs8I5FlU/Ny7qszxtrM3UCYbAgoF4SI+QsfAAXMekgPg0gd2aPsimd4JTV7Ft/BZBp4rn/I5Y01JHUFSribH7tkswcAk9oFVCrVP3TGDWhZGKCXEQg7+54W1fowhP2SkhDjiOJo0q/6Hydg9ZdGwO5Xc9EpPxt1MDoCjRiJZh2JK1XqkMJbcTtWSRQnug+hA=
  app: tragically-canoe-07528
  run: rails db:migrate
